[lib]
name = "gcode_rust_library"
path = "src/lib.rs"

[package]
name = "gcode_rust_library"
#name = "create_g_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
